@startuml
!pragma teoz true
skinparam SequenceMessageAlign direction
title Open Portfolio
participant Gateway
entity Portfolio
[-> Gateway : open portfolio
activate Gateway
Gateway -> Portfolio: openPortfolio
activate Portfolio
Portfolio --> Portfolio : allocate ID\nand store\ndetails
Portfolio -> Gateway : <PortfolioId>
deactivate Portfolio
[<- Gateway  : <PortfolioId>
deactivate Gateway
@enduml

