@startuml
!pragma teoz true
skinparam SequenceMessageAlign direction
title Sell order flow
actor Browser <<User>> order 1
participant Gateway order 2
entity Portfolio <<PersistentEntity>> order 3
collections OrderPlaced  <<Topic>> order 4
collections OrderResult <<Topic>> order 5
entity Broker <<PersistentEntity>> order 6
box "Portfolio Service"
  participant Portfolio
  participant OrderPlaced
end box
box "Broker Service"
  participant Broker
  participant OrderResult
end box
Browser -> Gateway: sell shares
activate Gateway
Gateway -> Portfolio: placeOrder
activate Portfolio
Portfolio --> Portfolio : confirm and\nremove shares
Portfolio -> OrderPlaced: OrderPlaced
& Portfolio -> Gateway: <OrderId>
deactivate Portfolio
activate OrderPlaced #blue
OrderPlaced -[#blue]->> Broker: OrderPlaced
activate Broker
deactivate OrderPlaced
Gateway -> Browser: OK
deactivate Gateway
Broker --> Broker: Find buyer
Broker -> OrderResult: Fulfilled
activate OrderResult #blue
deactivate Broker
OrderResult -[#blue]->> Portfolio: Fulfilled
& OrderResult -[#blue]->> Gateway: Fulfilled
activate Gateway
activate Portfolio
deactivate OrderResult
Gateway -> Browser: order update
& Portfolio --> Portfolio: Credit funds
deactivate Portfolio
deactivate Gateway
@enduml